# Generated by Django 2.0.2 on 2019-08-10 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaperInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('papername', models.CharField(max_length=500, unique=True)),
                ('journal', models.CharField(max_length=200)),
                ('fenqu', models.IntegerField()),
                ('top', models.BooleanField(default=False)),
                ('impactfactor', models.FloatField()),
                ('cites', models.IntegerField()),
                ('esi', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='UnsearchedPapers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('papername', models.CharField(max_length=500, unique=True)),
                ('journal', models.CharField(max_length=200)),
            ],
        ),
    ]
